config/routes.rb
Rails.application.routes.draw do
	resources :posts
	root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true,
             length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
    @posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
			redirect_to posts_path
		else
			render :new
		end
  end

  def show
  	@post = Post.find(params[:id])  	
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
			redirect_to posts_path, notice: "Post	was	successfully	created."
		else
			render :edit
		end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy

  	flash[:alert] = "Post deleted"
  	redirect_to posts_path
  end

  private
  	def post_params
  		params.require(:post).permit(:title, :content)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "common/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>Edit Post</h2>
    <hr>
    <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>
    Title
    <%= f.text_field :title %>
    <br>
    Content
    <br>
    <%= f.text_area :content %>
    <br>
    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="col-md-12">
  <h1>My Blog</h1>
  <div class="post">
    <%= link_to("New Post", new_post_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Content</td>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>#</td>
          <td><%= link_to(post.title, post_path(post)) %></td>
          <td><%= post.content %></td>
          <td>
              <%= link_to("Edit", edit_post_path(post), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", post_path(post),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>New Post</h2>
    <hr>
    <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>
    Title
    <%= f.text_field :title %>
    <br>
    Content
    <br>
    <%= f.text_area :content %>
    <br>
    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <div class="post">
    <%= link_to("Edit", edit_post_path(@post), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @post.title %></h2>
  <p><%= @post.content %></p>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>